image: python:3.12

services:
  - postgres:13
  - redis:6

variables:
  POSTGRES_DB: bikeapi
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: postgres
  DB_PORT: 5432
  REDIS_HOST: redis
  REDIS_PORT: 6379

before_script:
  - pip install poetry
  - poetry install
  - cp bikeapi/settings/ci_settings.py bikeapi/settings/local_settings.py
  - python manage.py wait_for_db
  - python manage.py migrate

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pytest --ds=bikeapi.settings.local_settings --cov=. --cov-report=xml

deploy:
  stage: deploy
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y lftp
    - lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST <<EOF
      mirror -R ./ /path/to/deploy
      quit
    EOF
