stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: bikeapi
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  DB_HOST: db
  DB_PORT: 5432
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

services:
  - name: postgres:13
    alias: db
  - name: redis:6
    alias: redis

before_script:
  - apk update && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev openssl-dev cargo make
  - pip install -r requirements.txt
  - python manage.py migrate

build:
  stage: build
  script:
    - echo "Building the application"
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests"
    - docker-compose run web pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying the application"
    - docker-compose up -d
  only:
    - main
