version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bikeapi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=bikeapi
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432

  celery:
    build: .
    command: celery -A bikeapi worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=bikeapi
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A bikeapi beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=bikeapi
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
